# Generated by Django 5.2.8 on 2025-11-26 07:35

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customers",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customers",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=myapp.models.profile_image_path
            ),
        ),
        migrations.AddField(
            model_name="customers",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customers",
            name="username",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
